### ISSUE TITLE
Issues with `json.load` in `generate_data.py`

### ISSUE THREAD

**Issue by Daulbaev** [pedrolarben/TimeSeriesForecasting-DeepLearning#1]
Hello! 

It seems that `DATASETS = json.load("../data/datasets.json")` and other `json.load` calls in `generate_data.py` do not work properly. This function should take not a filename but an object. 

P.S. Thank you for a nice repository!

**Comment by pedrolarben** [comment]
Thanks for pointing out this bug, @Daulbaev 
I have just fix it! https://github.com/pedrolarben/TimeSeriesForecasting-DeepLearning/commit/0ab952e8a6051237447a7b25bb9df41188433591

**Comment by Daulbaev** [comment]
Thanks!
